"""
expand_database.py
Adds 25 new biological strategies to biomimicry.db
Run from the project root:
    python scripts/expand_database.py
"""

import sqlite3
import os
import re

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "database", "biomimicry.db")

NEW_STRATEGIES = [
    {
        "organism": "Common octopus",
        "organism_scientific": "Octopus vulgaris",
        "kingdom": "Animal",
        "habitat": "Coastal ocean waters worldwide",
        "biological_function": "Changes skin color, texture, and pattern in milliseconds using chromatophores, papillae, and iridophores — achieving camouflage and communication on any background",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Communicate with color",
        "human_application": "Flexible electronic displays, adaptive camouflage fabrics for military, soft robots with variable stiffness skin",
        "real_world_products": "DARPA cephalopod-inspired camouflage program, Cornell soft robotics lab flexible skin",
        "industry_tags": "electronics, defense, robotics, textiles",
        "key_principle": "Overlapping layers of pigment cells, reflectors, and muscle-controlled papillae allow real-time, programmable surface appearance — all without rigid components",
        "source_url": "https://asknature.org/strategy/skin-changes-color-and-texture/",
        "slug": "octopus-chromatophores-adaptive-camouflage-displays",
    },
    {
        "organism": "Toco toucan",
        "organism_scientific": "Ramphastos toco",
        "kingdom": "Animal",
        "habitat": "South American tropical forest",
        "biological_function": "Uses its oversized hollow bill — a foam-filled composite of keratin tiles over a closed-cell bone foam — as a highly efficient heat radiator, dumping up to 400% of its resting heat through the beak",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Regulate temperature",
        "human_application": "Lightweight thermal management panels for electronics, energy-efficient building facades, aerospace heat exchangers",
        "real_world_products": "Research at MIT and University of Toronto on bio-inspired heat sinks",
        "industry_tags": "electronics, architecture, aerospace, energy",
        "key_principle": "A rigid closed-cell foam core covered by a stiff shell creates a light, strong structure with exceptional thermal conductivity — maximizing surface area while minimizing weight",
        "source_url": "https://asknature.org/strategy/bill-acts-as-thermal-radiator/",
        "slug": "toucan-beak-thermal-radiator-heat-management",
    },
    {
        "organism": "Polar bear",
        "organism_scientific": "Ursus maritimus",
        "kingdom": "Animal",
        "habitat": "Arctic sea ice",
        "biological_function": "Hollow, transparent fur fibers scatter and channel ultraviolet light down to the black skin beneath, providing solar heat gain while insulating against extreme cold",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Capture energy",
        "human_application": "Fiber-optic solar collectors, transparent insulation panels for passive solar buildings, improved cold-weather thermal garments",
        "real_world_products": "Research prototypes at several European passive solar labs",
        "industry_tags": "energy, architecture, textiles, materials science",
        "key_principle": "Optically transparent hollow fibers act as light pipes while trapping a layer of still air — separating light conduction from thermal insulation in the same structure",
        "source_url": "https://asknature.org/strategy/fur-traps-solar-energy/",
        "slug": "polar-bear-fur-solar-collector-thermal-insulation",
    },
    {
        "organism": "Common firefly",
        "organism_scientific": "Photinus pyralis",
        "kingdom": "Animal",
        "habitat": "Temperate woodlands and meadows, eastern North America",
        "biological_function": "Produces light via bioluminescence with near-100% efficiency — converting chemical energy to light with virtually zero heat loss",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Produce light",
        "human_application": "High-efficiency LED coatings that mimic the firefly's lantern microstructure to extract more light; bioluminescent biosensors for medical diagnostics",
        "real_world_products": "Improved LED light extraction coatings (Fudan University, 2013); luciferase-based lab diagnostic kits widely used in medicine",
        "industry_tags": "energy, electronics, medical devices, biotechnology",
        "key_principle": "A jagged microstructure of asymmetric scales on the lantern surface prevents internal reflection, allowing nearly all generated light to escape — the same principle now applied to LED packages",
        "source_url": "https://asknature.org/strategy/light-is-produced-efficiently/",
        "slug": "firefly-bioluminescence-efficient-led-lighting",
    },
    {
        "organism": "Moth (nocturnal moths)",
        "organism_scientific": "Various Lepidoptera",
        "kingdom": "Animal",
        "habitat": "Worldwide; nocturnal habitats",
        "biological_function": "Corneal nanostructures on moth eyes form a gradient refractive index that eliminates surface reflections across all wavelengths and angles — maximizing light capture at night while hiding the eye from predators",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect light",
        "human_application": "Anti-reflective coatings for solar panels, camera lenses, phone screens, and architectural glass — increasing transmission and reducing glare",
        "real_world_products": "Moth-eye film by Mitsubishi Rayon; Solarmer Energy moth-eye solar cells; anti-glare screen protectors",
        "industry_tags": "energy, electronics, materials science, optics",
        "key_principle": "A subwavelength array of tapered nanopillars creates a smooth transition in refractive index from air to substrate, eliminating the sharp interface that normally causes reflection",
        "source_url": "https://asknature.org/strategy/compound-eyes-minimize-reflectance/",
        "slug": "moth-eye-nanostructure-anti-reflective-coating",
    },
    {
        "organism": "Ruby-throated hummingbird",
        "organism_scientific": "Archilochus colubris",
        "kingdom": "Animal",
        "habitat": "Eastern North America; forest edges and gardens",
        "biological_function": "Hovers in place with precision by beating asymmetric figure-eight wingstrokes at 50-80 Hz, generating lift on both the downstroke and upstroke — the only bird capable of sustained backwards flight",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Move through air",
        "human_application": "Agile micro air vehicles (MAVs), drone stabilization systems, VTOL aircraft designs that can hover efficiently in confined spaces",
        "real_world_products": "AeroVironment Nano Hummingbird drone (DARPA); Harvard RoboBee; multiple academic MAV platforms",
        "industry_tags": "aerospace, robotics, defense",
        "key_principle": "A flexible, asymmetric wing that morphs on each stroke to maintain positive angle of attack in both directions generates lift continuously — unlike rigid propellers that waste half their cycle",
        "source_url": "https://asknature.org/strategy/wings-enable-hovering-flight/",
        "slug": "hummingbird-hovering-flight-micro-air-vehicles",
    },
    {
        "organism": "Physarum polycephalum (slime mold)",
        "organism_scientific": "Physarum polycephalum",
        "kingdom": "Protist",
        "habitat": "Moist forest floors and leaf litter worldwide",
        "biological_function": "Without a brain or nervous system, solves shortest-path problems between food sources by reinforcing efficient tubular connections and pruning redundant ones — recreating Tokyo's rail network topology when food is placed at city locations",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Coordinate behavior",
        "human_application": "Network design algorithms for roads, rail, internet routing, and supply chains; fault-tolerant distributed computing architectures",
        "real_world_products": "Toshiba slime-mold-inspired network routing chips; academic applications to internet topology design",
        "industry_tags": "computing, transportation, logistics, environmental technology",
        "key_principle": "Positive feedback reinforces high-throughput paths while oscillatory flow in tubes prunes low-efficiency routes — a decentralized optimization that balances efficiency with redundancy",
        "source_url": "https://asknature.org/strategy/network-is-optimized-without-central-control/",
        "slug": "slime-mold-network-optimization-distributed-computing",
    },
    {
        "organism": "Fire ant",
        "organism_scientific": "Solenopsis invicta",
        "kingdom": "Animal",
        "habitat": "South American floodplains; invasive worldwide",
        "biological_function": "When flooded, thousands of fire ants link legs and bodies into a self-assembling, waterproof raft that is unsinkable and self-repairing — any ant submerged at the bottom cycles to the top within minutes",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Form temporary bonds",
        "human_application": "Self-assembling modular robots, reconfigurable soft structures for search-and-rescue, dynamic architectural materials that adapt to load",
        "real_world_products": "Georgia Tech fire ant robotics research; MIT CSAIL modular robot swarms",
        "industry_tags": "robotics, materials science, architecture, defense",
        "key_principle": "Individual units with simple local rules (grab a neighbor, don't let go unless you're on top) collectively produce a stable, adaptable macrostructure without central coordination",
        "source_url": "https://asknature.org/strategy/ants-form-living-waterproof-rafts/",
        "slug": "fire-ant-raft-self-assembling-modular-robotics",
    },
    {
        "organism": "Lined seahorse",
        "organism_scientific": "Hippocampus erectus",
        "kingdom": "Animal",
        "habitat": "Atlantic coastal waters, seagrass beds",
        "biological_function": "The bony tail is built from square cross-section rings that slide and rotate against each other — absorbing impact 50% better than a circular cross-section and locking rigid under compression without fracturing",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Manage structural forces",
        "human_application": "Flexible armor for military and sports equipment, surgical robotics with controlled stiffness, grippers that can grab without crushing",
        "real_world_products": "Clemson University seahorse-tail armor prototypes; surgical robotics research at several institutions",
        "industry_tags": "defense, medical devices, robotics, materials science",
        "key_principle": "Interlocking square bony segments provide simultaneous flexibility, toughness, and compressive rigidity — a combination impossible with a smooth cylinder of the same material",
        "source_url": "https://asknature.org/strategy/tail-structure-resists-crushing/",
        "slug": "seahorse-tail-flexible-armor-surgical-robotics",
    },
    {
        "organism": "Whale shark",
        "organism_scientific": "Rhincodon typus",
        "kingdom": "Animal",
        "habitat": "Tropical and warm temperate ocean surfaces worldwide",
        "biological_function": "Filters up to 6,000 litres of water per hour through cephalic lobes using cross-flow filtration — particles are swept sideways off the filter surface rather than clogging it, allowing continuous high-volume water processing",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Filter matter",
        "human_application": "Self-cleaning water filtration membranes, desalination systems, industrial microparticle separation that resists fouling",
        "real_world_products": "Research at Shark Bay research institutes; applied membrane filtration design at several water treatment companies",
        "industry_tags": "water, environmental technology, food science, marine engineering",
        "key_principle": "Cross-flow rather than dead-end filtration prevents particle accumulation by keeping material in lateral motion — the filter stays clean because particles never stop moving across it",
        "source_url": "https://asknature.org/strategy/gills-filter-water-without-clogging/",
        "slug": "whale-shark-crossflow-filtration-water-treatment",
    },
    {
        "organism": "Sandcastle worm",
        "organism_scientific": "Phragmatopoma californica",
        "kingdom": "Animal",
        "habitat": "Pacific coast of North America, intertidal zones",
        "biological_function": "Secretes a two-part underwater adhesive from separate glands — a polyelectrolyte complex that sets hard within seconds in cold seawater, bonding sand grains into a precise tube structure",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Attach temporarily",
        "human_application": "Surgical tissue adhesives that work in wet conditions, underwater repair glues for marine structures, bone-bonding cements for orthopaedics",
        "real_world_products": "University of California Santa Barbara sandcastle worm glue research; multiple surgical adhesive patents",
        "industry_tags": "medical devices, marine engineering, construction, materials science",
        "key_principle": "Two oppositely charged protein solutions react on mixing to form a coacervate that is hydrophobic enough to displace water from a surface before curing — enabling adhesion where conventional glues fail",
        "source_url": "https://asknature.org/strategy/adhesive-works-underwater/",
        "slug": "sandcastle-worm-underwater-adhesive-surgical-glue",
    },
    {
        "organism": "Hagfish",
        "organism_scientific": "Myxine glutinosa",
        "kingdom": "Animal",
        "habitat": "Deep ocean floors worldwide",
        "biological_function": "When threatened, releases a small volume of mucus that expands 10,000-fold in a fraction of a second, forming a cohesive gel that clogs predator gills — made from protein threads finer than spider silk woven into a 3D network",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Deter predators",
        "human_application": "Ultra-strong lightweight fibres for body armour, impact-absorbing gels for helmets and protective equipment, novel hydrogel materials for medical implants",
        "real_world_products": "University of Guelph hagfish silk fibre research; US Navy interest in slime-based protective materials",
        "industry_tags": "defense, materials science, medical devices, textiles",
        "key_principle": "Protein fibres stored pre-coiled in mucus vesicles unravel and interlock explosively on contact with water — achieving structural complexity in milliseconds without any external energy input",
        "source_url": "https://asknature.org/strategy/slime-deters-predators/",
        "slug": "hagfish-slime-fiber-protective-materials",
    },
    {
        "organism": "Marine diatom",
        "organism_scientific": "Various Bacillariophyta",
        "kingdom": "Protist",
        "habitat": "Ocean and freshwater surfaces worldwide",
        "biological_function": "Single-celled algae build intricate silica shells (frustules) with species-specific nanoscale pore patterns — achieving maximum mechanical strength with minimum material, self-assembling at room temperature from dissolved silicon",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Use templates",
        "human_application": "Nanofabrication templates for photonic devices, drug delivery microparticles with controlled pore size, ultralight structural materials, solar cell light trapping layers",
        "real_world_products": "Diatomite filtration media (commercial); Oregon State University diatom-templated lithium-ion battery anodes; photonic diatom research at multiple labs",
        "industry_tags": "electronics, medical devices, materials science, energy",
        "key_principle": "Genetically encoded self-assembly produces hierarchical nano-to-micro porous silica structures with optical and mechanical properties that top-down nanofabrication struggles to replicate",
        "source_url": "https://asknature.org/strategy/silica-shell-provides-protection/",
        "slug": "diatom-silica-frustule-nanofabrication-templates",
    },
    {
        "organism": "Maple tree (samara seed)",
        "organism_scientific": "Acer saccharum",
        "kingdom": "Plant",
        "habitat": "Temperate deciduous forests, eastern North America",
        "biological_function": "The asymmetric single-winged seed (samara) autorotates as it falls, generating lift that reduces descent rate by 50% and disperses seeds up to 200m — using passive aerodynamics with zero moving parts",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Move through air",
        "human_application": "Single-wing micro air vehicles for environmental monitoring, slow-descending sensor pods for search and rescue, passive wind energy rotors",
        "real_world_products": "Lockheed Martin Samarai maple seed drone; Aerovironment inspired samara concepts; Harvard SEAS spinning seed robots",
        "industry_tags": "aerospace, robotics, defense, energy",
        "key_principle": "A curved aerofoil offset from the centre of mass induces autorotation that generates upward lift as the system falls — stable, predictable, and requiring no power or control surfaces",
        "source_url": "https://asknature.org/strategy/seeds-disperse-by-autorotation/",
        "slug": "maple-samara-autorotation-micro-air-vehicles",
    },
    {
        "organism": "Nautilus",
        "organism_scientific": "Nautilus pompilius",
        "kingdom": "Animal",
        "habitat": "Deep Indo-Pacific ocean slopes",
        "biological_function": "The shell is divided into gas-filled chambers connected by a siphuncle tube — allowing the nautilus to precisely control buoyancy at depths up to 800m by adjusting gas and fluid ratios, surviving pressures that crush most submarines",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Control buoyancy",
        "human_application": "Submarine buoyancy control systems, deep-sea pressure vessel design, lightweight structural shells using the logarithmic spiral geometry",
        "real_world_products": "Nautilus shell geometry used in fan blade design (PAX Scientific); military submarine chamber design research",
        "industry_tags": "marine engineering, aerospace, architecture, materials science",
        "key_principle": "A logarithmic spiral of progressively larger chambers distributes hoop stress evenly throughout the shell — achieving maximum pressure resistance with minimum material at every point",
        "source_url": "https://asknature.org/strategy/shell-withstands-high-pressure/",
        "slug": "nautilus-shell-pressure-vessel-buoyancy-design",
    },
    {
        "organism": "Rattlesnake",
        "organism_scientific": "Crotalus atrox",
        "kingdom": "Animal",
        "habitat": "North American deserts and scrublands",
        "biological_function": "Detects infrared radiation (body heat) from prey using pit organs containing a thin membrane just 15 micrometres thick — resolving temperature differences of 0.003°C at distances up to one metre in total darkness",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect heat",
        "human_application": "Ultra-sensitive infrared sensors for night vision, search-and-rescue heat detectors, thermal cameras for medical diagnostics and building energy audits",
        "real_world_products": "DARPA pit-organ inspired uncooled IR sensors; University of California Berkeley graphene IR detector based on pit membrane geometry",
        "industry_tags": "defense, medical devices, electronics, energy",
        "key_principle": "An air-backed membrane with minimal thermal mass maximises the temperature differential caused by incoming IR — creating a natural bolometer far more sensitive per unit area than most engineered equivalents",
        "source_url": "https://asknature.org/strategy/pit-organs-detect-infrared-radiation/",
        "slug": "rattlesnake-pit-organ-infrared-sensor-thermal-camera",
    },
    {
        "organism": "Leaf venation (dicot leaves)",
        "organism_scientific": "Various angiosperms",
        "kingdom": "Plant",
        "habitat": "Worldwide",
        "biological_function": "Hierarchical branching networks in leaves deliver water and nutrients to every cell within 1-2 cells of a vein, while the looped (reticulate) topology ensures continued delivery even after veins are severed — combining efficiency with damage tolerance",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Distribute resources",
        "human_application": "Efficient heat exchanger designs, microfluidic lab-on-chip devices, resilient power grid and internet topology, urban water distribution network planning",
        "real_world_products": "Leaf venation-inspired microfluidic cooling chips (IBM); fractal heat exchangers in aerospace; urban planning research at MIT Media Lab",
        "industry_tags": "energy, electronics, architecture, computing",
        "key_principle": "A hierarchy of vein sizes (primary, secondary, tertiary) minimises total transport resistance while reticulate loops provide redundant paths — optimising for both efficiency and robustness simultaneously",
        "source_url": "https://asknature.org/strategy/veins-distribute-water-and-nutrients/",
        "slug": "leaf-venation-network-heat-exchanger-microfluidics",
    },
    {
        "organism": "American crocodile",
        "organism_scientific": "Crocodylus acutus",
        "kingdom": "Animal",
        "habitat": "Coastal waters, Florida and Caribbean",
        "biological_function": "Thousands of dome-shaped sensory organs (integumentary sense organs) embedded in the scutes detect pressure, vibration, and salinity changes in water with extreme sensitivity — allowing the crocodile to detect ripples from a single water droplet in total darkness",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect pressure",
        "human_application": "Soft robotic skin with distributed pressure sensing, artificial lateral line systems for underwater vehicles, prosthetic limbs with tactile feedback",
        "real_world_products": "MIT CSAIL crocodile-inspired pressure sensor arrays; underwater robot skin research at several labs",
        "industry_tags": "robotics, medical devices, marine engineering, defense",
        "key_principle": "Dense arrays of mechanoreceptors with different frequency responses embedded in flexible skin produce a spatial map of pressure fields — giving whole-body situational awareness without rigid sensors",
        "source_url": "https://asknature.org/strategy/sense-organs-detect-water-movement/",
        "slug": "crocodile-skin-pressure-sensors-soft-robotics",
    },
    {
        "organism": "Bactrian camel",
        "organism_scientific": "Camelus bactrianus",
        "kingdom": "Animal",
        "habitat": "Central Asian deserts and steppes",
        "biological_function": "Tolerates 30% body water loss, body temperature swings of 6°C over a day, and fat stored in humps (not water) that provides energy while reducing metabolic heat load — surviving extreme heat and cold through physiology alone",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Regulate temperature",
        "human_application": "Passive building cooling strategies that allow indoor temperature to fluctuate within a comfort range to reduce HVAC load; phase-change thermal storage materials; dehydration-tolerant medical implants",
        "real_world_products": "Thermal mass building design principles derived from camel thermoregulation; phase-change wall panels (various manufacturers)",
        "industry_tags": "architecture, energy, medical devices, textiles",
        "key_principle": "Allowing body temperature to rise during the day acts as a thermal buffer — absorbing heat that would otherwise require cooling energy, then radiating it at night when the environment is cold",
        "source_url": "https://asknature.org/strategy/body-temperature-fluctuates-to-conserve-water/",
        "slug": "camel-thermoregulation-passive-building-cooling",
    },
    {
        "organism": "Emperor penguin",
        "organism_scientific": "Aptenodytes forsteri",
        "kingdom": "Animal",
        "habitat": "Antarctic sea ice",
        "biological_function": "Huddles of thousands of penguins rotate continuously — outer penguins move inward and warm penguins move outward — maintaining a steady 37°C core temperature for the group in -40°C winds with no individual staying cold indefinitely",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Regulate temperature",
        "human_application": "Collective thermal management in data centres and battery packs, self-organising swarm robot coordination, optimised crowd flow and stadium design",
        "real_world_products": "Huawei data centre cooling algorithms inspired by penguin huddles; battery thermal management research at several EV labs",
        "industry_tags": "energy, computing, robotics, architecture",
        "key_principle": "Decentralised movement rules (move in when cold, move out when warm) produce collective thermoregulation that is more efficient and fault-tolerant than any centralised heating system",
        "source_url": "https://asknature.org/strategy/huddles-maintain-body-temperature/",
        "slug": "penguin-huddle-collective-thermal-management",
    },
    {
        "organism": "Mycorrhizal fungi network",
        "organism_scientific": "Various Basidiomycota and Glomeromycota",
        "kingdom": "Fungi",
        "habitat": "Forest soil worldwide; symbiotic with ~90% of land plant species",
        "biological_function": "Extends plant root reach up to 100-fold via fungal hyphae that trade phosphorus, water, and minerals for plant sugars — also transferring carbon and distress signals between trees over kilometres in a self-repairing underground network",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Coordinate behaviour",
        "human_application": "Resilient decentralised communication networks, peer-to-peer internet architectures, fault-tolerant supply chain design, carbon sequestration strategies",
        "real_world_products": "P2P internet routing protocols inspired by mycorrhizal topology; Ecovative mycelium packaging (uses fungi directly); academic distributed systems research",
        "industry_tags": "computing, environmental technology, agriculture, logistics",
        "key_principle": "A mesh network with no central hub, where connections strengthen with use and are pruned when redundant, delivers extraordinary resilience — if one path fails, material reroutes automatically through the mesh",
        "source_url": "https://asknature.org/strategy/fungi-network-resources-through-mycelium/",
        "slug": "mycorrhizal-network-distributed-computing-internet",
    },
    {
        "organism": "Starling murmuration",
        "organism_scientific": "Sturnus vulgaris",
        "kingdom": "Animal",
        "habitat": "Europe and western Asia; open farmland and reedbeds",
        "biological_function": "Flocks of up to a million starlings produce fluid, shapeshifting aerial formations with no leader — each bird follows three simple rules relative to its seven nearest neighbours, producing coordinated evasion of predators and collision-free flight",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Move in groups",
        "human_application": "Swarm robotics coordination, autonomous drone fleet management, traffic flow optimisation, collective AI for multi-agent systems",
        "real_world_products": "Swarmanoid project (EPFL/ULB); Amazon warehouse robot coordination; multiple autonomous vehicle platooning systems",
        "industry_tags": "robotics, transportation, computing, defense",
        "key_principle": "Local interaction rules applied consistently across thousands of individuals produce emergent global behaviour that is cohesive, adaptive, and requires no central control or communication beyond line-of-sight",
        "source_url": "https://asknature.org/strategy/flocking-behavior-provides-protection/",
        "slug": "starling-murmuration-swarm-robotics-autonomous-drones",
    },
    {
        "organism": "Tardigrade (water bear)",
        "organism_scientific": "Ramazzottius varieornatus",
        "kingdom": "Animal",
        "habitat": "Everywhere — from Himalayan mountaintops to deep ocean trenches to Antarctic ice",
        "biological_function": "Enters cryptobiosis by replacing cellular water with a glass-like sugar (trehalose) and producing unique proteins (Dsup) that physically shield DNA — surviving vacuum, radiation 1,000× the lethal human dose, temperatures from -272°C to 150°C, and 30 years without water",
        "biomimicry_taxonomy_group": "Modify",
        "biomimicry_taxonomy_subgroup": "Change state",
        "human_application": "Room-temperature storage of vaccines and biologics without refrigeration, radiation-hardened electronics, DNA damage-resistant cancer treatments, long-duration space mission biology",
        "real_world_products": "Biomatik trehalose-based dry storage products; University of Tokyo Dsup protein used to protect human cells from radiation; NASA tardigrade space experiments",
        "industry_tags": "biotechnology, medical devices, defense, food science",
        "key_principle": "Vitrification — replacing liquid water with an amorphous solid glass — suspends all biological processes while preserving molecular structure, allowing perfect resumption when water returns",
        "source_url": "https://asknature.org/strategy/survives-extreme-dehydration/",
        "slug": "tardigrade-cryptobiosis-vaccine-storage-radiation",
    },
    {
        "organism": "Veiled chameleon",
        "organism_scientific": "Chamaeleo calyptratus",
        "kingdom": "Animal",
        "habitat": "Arabian Peninsula mountain forests and valleys",
        "biological_function": "Rapidly shifts skin color through active tuning of iridophore crystal lattice spacing — changing reflected wavelength (and therefore color) in seconds for camouflage and communication, not pigment chemistry",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Communicate with color",
        "human_application": "Electrochromic smart windows that switch tint, electronic ink displays, adaptive military camouflage, structural color materials that never fade",
        "real_world_products": "MIT Media Lab chameleon-inspired structural color research; SageGlass electrochromic smart windows (related principle); DARPA adaptive camouflage programs",
        "industry_tags": "architecture, defense, electronics, materials science",
        "key_principle": "Mechanically tuning the spacing of a photonic crystal lattice shifts which wavelength it reflects — producing vivid, fadeless color change from a single transparent material with no pigments",
        "source_url": "https://asknature.org/strategy/skin-color-changes-by-tuning-crystals/",
        "slug": "chameleon-photonic-crystal-smart-windows-camouflage",
    },
    {
        "organism": "African elephant",
        "organism_scientific": "Loxodonta africana",
        "kingdom": "Animal",
        "habitat": "Sub-Saharan African savanna and forest",
        "biological_function": "The trunk contains ~150,000 muscle fascicles and no rigid skeleton — achieving six degrees of freedom, delicate object manipulation (picking up a single grape), and the strength to uproot trees, all in one appendage",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Manipulate objects",
        "human_application": "Soft robotic arms with human-safe compliance, flexible surgical instruments, grippers that handle fragile objects without sensing, prosthetic limbs with natural movement",
        "real_world_products": "Festo Bionic Cobot (elephant trunk-inspired soft arm); multiple surgical robotics platforms; soft gripper startups including Soft Robotics Inc.",
        "industry_tags": "robotics, medical devices, manufacturing, aerospace",
        "key_principle": "Muscular hydrostats — structures that maintain constant volume while changing shape — achieve complex motion through antagonistic muscle pairs without joints, bearings, or rigid links",
        "source_url": "https://asknature.org/strategy/trunk-manipulates-objects-with-precision/",
        "slug": "elephant-trunk-soft-robotics-flexible-manipulation",
    },
]


def slugify(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    return text


def main():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Fetch existing slugs to avoid duplicates
    c.execute("SELECT slug FROM strategies")
    existing_slugs = {row[0] for row in c.fetchall()}

    added = 0
    skipped = 0

    for s in NEW_STRATEGIES:
        if s["slug"] in existing_slugs:
            print(f"  SKIP (already exists): {s['slug']}")
            skipped += 1
            continue

        c.execute(
            """
            INSERT INTO strategies (
                organism, organism_scientific, kingdom, habitat,
                biological_function, biomimicry_taxonomy_group,
                biomimicry_taxonomy_subgroup, human_application,
                real_world_products, industry_tags, key_principle,
                source_url, slug
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
            """,
            (
                s["organism"],
                s["organism_scientific"],
                s["kingdom"],
                s["habitat"],
                s["biological_function"],
                s["biomimicry_taxonomy_group"],
                s["biomimicry_taxonomy_subgroup"],
                s["human_application"],
                s["real_world_products"],
                s["industry_tags"],
                s["key_principle"],
                s["source_url"],
                s["slug"],
            ),
        )
        print(f"  ADDED: {s['organism']}")
        added += 1

    conn.commit()
    conn.close()

    c2 = sqlite3.connect(DB_PATH).cursor()
    c2.execute("SELECT COUNT(*) FROM strategies")
    total = c2.fetchone()[0]

    print(f"\nDone. Added {added}, skipped {skipped}. Total strategies: {total}")


if __name__ == "__main__":
    main()
