"""
seed_database.py — Creates and seeds the biomimicry SQLite database.
Run once to initialize: python scripts/seed_database.py
"""

import sqlite3
import os
import re

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "database", "biomimicry.db")


def slugify(text):
    """Convert text to a URL-friendly slug."""
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text.strip("-")


def create_schema(conn):
    conn.execute("""
        CREATE TABLE IF NOT EXISTS strategies (
            id INTEGER PRIMARY KEY,
            organism TEXT NOT NULL,
            organism_scientific TEXT,
            kingdom TEXT,
            habitat TEXT,
            biological_function TEXT,
            biomimicry_taxonomy_group TEXT,
            biomimicry_taxonomy_subgroup TEXT,
            human_application TEXT,
            real_world_products TEXT,
            industry_tags TEXT,
            key_principle TEXT,
            source_url TEXT,
            slug TEXT UNIQUE NOT NULL
        )
    """)
    conn.commit()


# 50 well-researched biological strategies
STRATEGIES = [
    {
        "organism": "Tokay gecko",
        "organism_scientific": "Gekko gecko",
        "kingdom": "Animal",
        "habitat": "Southeast Asian rainforests and rocky outcrops",
        "biological_function": "Millions of microscopic hair-like structures called setae on the gecko's toe pads create van der Waals forces — weak molecular attractions — that collectively produce enough adhesive force to support the animal's full body weight on glass, yet release instantly with a simple toe angle change.",
        "biomimicry_taxonomy_group": "Attach",
        "biomimicry_taxonomy_subgroup": "Attach temporarily",
        "human_application": "Dry adhesive tapes and pads that stick to almost any surface without glue, residue, or suction. Useful for robotics grippers, medical wound closure, and reusable fasteners.",
        "real_world_products": "Geckskin (UMass Amherst), Draper Laboratory gecko-inspired climbing robot, NASA spacecraft docking adhesives",
        "industry_tags": "materials science, robotics, medical devices, aerospace",
        "key_principle": "Hierarchical micro- and nano-scale fibrillar structures create intermolecular adhesion that is strong in shear but releases cleanly when the angle changes — no chemistry needed.",
        "source_url": "https://asknature.org/strategy/adhesion-is-achieved-with-micro-hairs/",
        "slug": "gecko-adhesion-dry-adhesives",
    },
    {
        "organism": "Sacred lotus",
        "organism_scientific": "Nelumbo nucifera",
        "kingdom": "Plant",
        "habitat": "Muddy ponds and slow-moving rivers across Asia",
        "biological_function": "The lotus leaf surface is covered with microscopic waxy bumps (papillae) that repel water so effectively that droplets bead up and roll off, carrying dirt particles with them. This keeps the leaf clean despite growing in muddy water — a phenomenon called superhydrophobicity.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Regulate surface properties",
        "human_application": "Self-cleaning coatings for fabrics, glass, building materials, and medical implants that repel water, dirt, and bacteria without chemical cleaning.",
        "real_world_products": "Lotusan exterior paint (Sto AG), Schoeller textile treatments, self-cleaning roof tiles",
        "industry_tags": "materials science, architecture, textiles, medical devices",
        "key_principle": "A micro-rough surface coated with hydrophobic wax creates a composite solid-air interface that maximizes water contact angle, causing droplets to roll rather than spread.",
        "source_url": "https://asknature.org/strategy/superhydrophobic-surfaces-stay-clean/",
        "slug": "lotus-leaf-self-cleaning-superhydrophobic",
    },
    {
        "organism": "Shortfin mako shark",
        "organism_scientific": "Isurus oxyrinchus",
        "kingdom": "Animal",
        "habitat": "Open ocean, worldwide temperate and tropical seas",
        "biological_function": "Tiny tooth-like scales called denticles cover the shark's skin in a precise pattern that disrupts the boundary layer of water, reducing turbulent drag. The riblet geometry channels water flow and creates small vortices that actually pull the shark forward.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Move through fluids",
        "human_application": "Drag-reducing riblet films for aircraft fuselages, ship hulls, and swimsuits. Also antimicrobial surfaces because bacteria cannot colonize the textured geometry.",
        "real_world_products": "Speedo Fastskin swimsuit, Sharklet antimicrobial surface (Sharklet Technologies), Airbus riblet film trials",
        "industry_tags": "aerospace, marine transport, textiles, medical devices",
        "key_principle": "Precisely spaced riblet microstructures align with flow direction to manage the turbulent boundary layer, reducing skin-friction drag by up to 10%.",
        "source_url": "https://asknature.org/strategy/skin-reduces-drag/",
        "slug": "shark-skin-denticles-drag-reduction",
    },
    {
        "organism": "Common kingfisher",
        "organism_scientific": "Alcedo atthis",
        "kingdom": "Animal",
        "habitat": "Rivers, lakes, and streams across Europe, Asia, and Africa",
        "biological_function": "The kingfisher dives from air into water — two media with very different densities — without making a splash. Its long, gradually tapering beak acts as a shape-optimized pressure wave manager, smoothly transitioning between media by minimizing the pressure differential at the tip.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Move through media interfaces",
        "human_application": "Redesigning the nose of Japan's Shinkansen bullet train to eliminate the loud sonic boom (tunnel boom) that occurred when trains exited tunnels at high speed. The new nose shape also reduced energy consumption by 15%.",
        "real_world_products": "Shinkansen 500-series bullet train nose (West Japan Railway), quieter high-speed rail designs worldwide",
        "industry_tags": "transportation, aerospace, engineering",
        "key_principle": "A gradually tapering, asymmetric profile minimizes pressure wave generation when transitioning between media of different densities — applicable to any high-speed vehicle entering a constricted space.",
        "source_url": "https://asknature.org/strategy/beak-shape-smooths-water-entry/",
        "slug": "kingfisher-beak-shinkansen-bullet-train",
    },
    {
        "organism": "African termite (Macrotermes michaelseni)",
        "organism_scientific": "Macrotermes michaelseni",
        "kingdom": "Animal",
        "habitat": "Sub-Saharan African savanna",
        "biological_function": "Termite mounds maintain a near-constant internal temperature of 31°C despite outside temperatures swinging from 1°C at night to 40°C during the day. A network of tunnels and vents acts as a passive lung: hot air rises through a central chimney, draws cool air in through basement vents, and the porous mound wall exchanges gases and heat with the outside.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Regulate temperature",
        "human_application": "Passively ventilated buildings that maintain comfortable temperatures without mechanical air conditioning, dramatically reducing energy costs in hot climates.",
        "real_world_products": "Eastgate Centre (Harare, Zimbabwe, architect Mick Pearce), CH2 Building (Melbourne, Australia)",
        "industry_tags": "architecture, energy, HVAC",
        "key_principle": "Distributed thermal mass combined with a network of convective flow channels creates a self-regulating temperature system driven entirely by natural pressure differentials.",
        "source_url": "https://asknature.org/strategy/mound-maintains-temperature/",
        "slug": "termite-mound-passive-ventilation-architecture",
    },
    {
        "organism": "Golden silk orb-weaver spider",
        "organism_scientific": "Nephila clavipes",
        "kingdom": "Animal",
        "habitat": "Tropical and subtropical forests worldwide",
        "biological_function": "Spider silk is five times stronger than steel by weight, yet more elastic than nylon. The protein-based fiber is spun at room temperature using water as a solvent, achieving a combination of tensile strength and toughness that no human-made fiber can match.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Make fibers and threads",
        "human_application": "Ultra-strong biodegradable fibers for bulletproof materials, medical sutures, parachute cords, and lightweight structural composites.",
        "real_world_products": "Bolt Threads synthetic spider silk, Spiber (Japan) structural proteins, AMSilk biosilk for cosmetics and medical applications",
        "industry_tags": "materials science, medical devices, defense, textiles",
        "key_principle": "Beta-sheet protein nanocrystals embedded in an amorphous matrix create a hierarchical structure that is simultaneously stiff (crystalline regions) and flexible (amorphous regions), dissipating energy without fracture.",
        "source_url": "https://asknature.org/strategy/silk-is-stronger-than-steel/",
        "slug": "spider-silk-tensile-strength-synthetic-fibers",
    },
    {
        "organism": "Humpback whale",
        "organism_scientific": "Megaptera novaeangliae",
        "kingdom": "Animal",
        "habitat": "All major oceans, migratory between polar feeding grounds and tropical breeding grounds",
        "biological_function": "Despite weighing up to 40 tonnes, humpback whales are remarkably agile, executing tight turns to herd fish. The leading edge of their flippers has large bumps (tubercles) that prevent stalling at high angles of attack by creating small vortices that keep airflow attached to the flipper surface.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Manage fluid flow",
        "human_application": "Tubercle-inspired leading edges on wind turbine blades improve efficiency at low wind speeds and reduce noise. Also applied to aircraft wings and industrial fans.",
        "real_world_products": "WhalePower Corp wind turbine blade retrofits, tubercle-edge fans (Envira-North Systems), aircraft winglet designs",
        "industry_tags": "energy, aerospace, marine transport",
        "key_principle": "Sinusoidal leading-edge bumps generate chordwise vortices that energize the boundary layer, delaying flow separation and maintaining lift at angles of attack that would otherwise cause stall.",
        "source_url": "https://asknature.org/strategy/bumpy-flippers-improve-maneuverability/",
        "slug": "humpback-whale-tubercles-wind-turbines",
    },
    {
        "organism": "Morpho butterfly",
        "organism_scientific": "Morpho menelaus",
        "kingdom": "Animal",
        "habitat": "Tropical rainforests of Central and South America",
        "biological_function": "The Morpho butterfly's brilliant iridescent blue color contains no blue pigment. Instead, microscopic layered structures on each wing scale act as a photonic crystal, selectively reflecting only blue wavelengths through constructive interference. The color shifts with viewing angle.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Produce and manipulate light",
        "human_application": "Structural color technology for anti-counterfeiting security features, high-visibility displays that work in bright sunlight, and colorfast textiles that never fade.",
        "real_world_products": "Qualcomm Mirasol display technology, Morphotex structural color fiber (Teijin), currency security holograms",
        "industry_tags": "materials science, electronics, security, textiles",
        "key_principle": "Nano-scale periodic structures with spacing matched to specific light wavelengths produce vivid, angle-dependent color through optical interference rather than chemical pigmentation — making the color permanent and fade-proof.",
        "source_url": "https://asknature.org/strategy/wing-scales-create-iridescent-color/",
        "slug": "morpho-butterfly-structural-color-anti-counterfeiting",
    },
    {
        "organism": "Cocklebur",
        "organism_scientific": "Xanthium strumarium",
        "kingdom": "Plant",
        "habitat": "Disturbed habitats worldwide — roadsides, agricultural fields",
        "biological_function": "The cocklebur seed pod is covered with hundreds of stiff hooks that terminate in a curved tip. These hooks snag on animal fur or clothing fibers and hold tenaciously until the hook is bent away from its natural curve, allowing seeds to travel far from the parent plant.",
        "biomimicry_taxonomy_group": "Attach",
        "biomimicry_taxonomy_subgroup": "Attach temporarily",
        "human_application": "Velcro — the hook-and-loop fastening system used in clothing, medical devices, aerospace, and consumer products worldwide. One of the most commercially successful biomimicry examples in history.",
        "real_world_products": "Velcro (Velcro Companies), used in NASA spacesuits, military gear, medical braces, children's shoes",
        "industry_tags": "textiles, medical devices, aerospace, consumer products",
        "key_principle": "Rigid hooks engaging with flexible loops create a releasable fastening that is strong in tension but releases easily when peeled — a simple geometry that requires no tools or adhesives.",
        "source_url": "https://asknature.org/strategy/burrs-attach-to-passing-animals/",
        "slug": "cocklebur-velcro-hook-loop-fastening",
    },
    {
        "organism": "California mussel",
        "organism_scientific": "Mytilus californianus",
        "kingdom": "Animal",
        "habitat": "Rocky intertidal zones along the Pacific coast of North America",
        "biological_function": "Mussels anchor themselves to rocks in crashing surf using thread-like byssal fibers tipped with adhesive plaques. The adhesive proteins (mfps — mussel foot proteins) bond to almost any wet surface, including rock, glass, and Teflon, despite the surf constantly trying to wash them away.",
        "biomimicry_taxonomy_group": "Attach",
        "biomimicry_taxonomy_subgroup": "Attach permanently",
        "human_application": "Underwater adhesives for surgical wound closure, dental bonding, and marine structure repair. The DOPA amino acid found in mussel adhesive proteins is the key to wet-surface bonding.",
        "real_world_products": "Mussel-inspired surgical glue (Karaoke, MIT research), Mytus adhesive, underwater repair compounds",
        "industry_tags": "medical devices, marine engineering, construction",
        "key_principle": "Catechol groups (DOPA) form reversible coordination bonds and covalent cross-links with metal oxides on wet surfaces, displacing water molecules to achieve adhesion where conventional glues fail.",
        "source_url": "https://asknature.org/strategy/adhesive-proteins-bond-to-wet-surfaces/",
        "slug": "mussel-adhesive-proteins-underwater-surgical-glue",
    },
    {
        "organism": "Boxfish (Ostracion cubicus)",
        "organism_scientific": "Ostracion cubicus",
        "kingdom": "Animal",
        "habitat": "Coral reefs of the Indo-Pacific",
        "biological_function": "Despite its boxy shape, the boxfish is remarkably hydrodynamic, generating self-correcting vortices around its body as it swims. Its rigid carapace acts as a passive stabilizer: when current pushes the fish sideways, the shape automatically generates a restoring force.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Maintain stability in fluids",
        "human_application": "Vehicle body shapes with low aerodynamic drag and passive stability. The boxfish inspired the Mercedes-Benz Bionic concept car, which achieved 20% lower drag than conventional designs.",
        "real_world_products": "Mercedes-Benz Bionic concept car, boxfish-inspired AUV (autonomous underwater vehicle) designs",
        "industry_tags": "transportation, marine engineering, aerospace",
        "key_principle": "A convex hull shape generates leading-edge vortices that provide passive hydrodynamic stability, reducing the energy needed for active course correction.",
        "source_url": "https://asknature.org/strategy/boxlike-body-is-hydrodynamic/",
        "slug": "boxfish-aerodynamics-mercedes-bionic-car",
    },
    {
        "organism": "Namibian fog-basking beetle",
        "organism_scientific": "Stenocara gracilipes",
        "kingdom": "Animal",
        "habitat": "Namib Desert, southwestern Africa",
        "biological_function": "In one of the world's driest habitats, this beetle collects drinking water from early-morning coastal fog. Its back has alternating hydrophilic (water-attracting) bumps and hydrophobic (water-repelling) troughs. Fog droplets accumulate on the bumps, grow large enough to overcome adhesion, then roll down the troughs straight to the beetle's mouth.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Collect and store water",
        "human_application": "Fog-harvesting nets, self-filling water bottles, water collection meshes for arid regions, and moisture-condensing surfaces for HVAC systems and architectural applications.",
        "real_world_products": "Warka Water tower (Architecture and Vision), NBD Nano fog-harvesting coating, FogQuest fog collection nets",
        "industry_tags": "water, architecture, materials science, humanitarian technology",
        "key_principle": "Patterning surfaces with alternating wettability — hydrophilic nucleation sites and hydrophobic transport channels — passively collects and channels atmospheric water without energy input.",
        "source_url": "https://asknature.org/strategy/fog-basking-collects-water/",
        "slug": "namibian-beetle-fog-collection-water-harvesting",
    },
    {
        "organism": "Honeybee",
        "organism_scientific": "Apis mellifera",
        "kingdom": "Animal",
        "habitat": "Every continent except Antarctica; domesticated worldwide",
        "biological_function": "Honeybees build honeycomb from beeswax using hexagonal cells packed together. This geometry is mathematically optimal: hexagons tile a plane perfectly with the minimum perimeter needed to enclose a given area, meaning the bees use less wax per cell while maximizing storage volume.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Optimize structural geometry",
        "human_application": "Lightweight aerospace sandwich panels, impact-absorbing packaging, structural core materials for aircraft flooring, wind turbine blades, and architectural facades.",
        "real_world_products": "Hexcel aerospace honeycomb panels, IKEA honeycomb cardboard furniture, Nomex honeycomb fire-resistant panels",
        "industry_tags": "aerospace, architecture, packaging, materials science",
        "key_principle": "The hexagonal tessellation achieves the highest area-to-perimeter ratio of any regular polygon, and the resulting sandwich structure has an extremely high stiffness-to-weight ratio by separating load-bearing skins with a lightweight core.",
        "source_url": "https://asknature.org/strategy/honeycomb-maximizes-storage/",
        "slug": "honeycomb-structure-aerospace-lightweight-panels",
    },
    {
        "organism": "European pinecone",
        "organism_scientific": "Pinus sylvestris",
        "kingdom": "Plant",
        "habitat": "European and Asian temperate forests",
        "biological_function": "Pinecone scales open when dry to release seeds and close when wet to protect them. The scale is made of two layers of cells with different expansion rates: the outer layer swells more in humidity, bending the scale closed without any muscles or brain — a purely mechanical response to moisture.",
        "biomimicry_taxonomy_group": "Modify",
        "biomimicry_taxonomy_subgroup": "Change shape in response to stimuli",
        "human_application": "Humidity-responsive building facades that open windows or vents as indoor humidity rises, self-ventilating sportswear that opens pores when the wearer sweats, and hygroscopic actuators for soft robotics.",
        "real_world_products": "HygroSkin pavilion (Achim Menges, Stuttgart), Mitsui temperature-responsive fabric, biomimetic architectural facade research at Harvard",
        "industry_tags": "architecture, textiles, robotics, energy",
        "key_principle": "Bilayer structures of materials with different hygroscopic or thermal expansion coefficients create autonomous, reversible shape changes in response to environmental conditions — no energy input, no control system.",
        "source_url": "https://asknature.org/strategy/scales-open-and-close-in-response-to-humidity/",
        "slug": "pinecone-humidity-responsive-adaptive-facades",
    },
    {
        "organism": "Pileated woodpecker",
        "organism_scientific": "Dryocopus pileatus",
        "kingdom": "Animal",
        "habitat": "Mature forests of North America",
        "biological_function": "Woodpeckers peck at up to 20 times per second, decelerating at 1,200 g each impact — enough to cause severe brain damage in any other animal. Four structures work together: a thick skull, a brain surrounded by minimal cerebrospinal fluid, a beak with unequal lengths to distribute force, and a hyoid bone that wraps around the skull as a shock absorber.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Manage impact forces",
        "human_application": "Multi-layer protective helmet designs, black box flight recorder casings, and impact-absorbing packaging systems inspired by the woodpecker's nested shock-absorption architecture.",
        "real_world_products": "Woodpecker-inspired bicycle helmet (Berkeley research), military helmet liner concepts, crash-resistant electronic casing designs",
        "industry_tags": "sports equipment, aerospace, defense, packaging",
        "key_principle": "Hierarchical shock absorption using multiple materials with graduated stiffness — from hard outer shell to increasingly compliant inner layers — dissipates impact energy across structures and timescales rather than concentrating stress.",
        "source_url": "https://asknature.org/strategy/skull-absorbs-impact/",
        "slug": "woodpecker-skull-shock-absorption-helmets",
    },
    {
        "organism": "Bombardier beetle",
        "organism_scientific": "Brachinus crepitans",
        "kingdom": "Animal",
        "habitat": "Meadows, gardens, and woodland edges across Europe and Asia",
        "biological_function": "The bombardier beetle defends itself by mixing hydroquinone and hydrogen peroxide from separate body chambers. When combined in a reaction chamber with catalytic enzymes, they undergo a rapid exothermic reaction that produces a boiling, toxic spray — ejected as a precisely aimed 100°C pulse at 500 pulses per second.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Produce defensive chemicals",
        "human_application": "Pulsed combustion engines and needle-free drug injection systems. The beetle's pulse-jet mechanism inspired more efficient combustion and precise pharmaceutical aerosol delivery.",
        "real_world_products": "AeroMed needle-free injection device, Leeds University pulsed combustion research",
        "industry_tags": "medical devices, energy, defense",
        "key_principle": "Rapid, pulsed mixing of two reactive chemicals in a catalyst-lined chamber produces a high-pressure, high-temperature output — a micro-scale pulse jet that is more efficient than continuous-flow equivalents.",
        "source_url": "https://asknature.org/strategy/bombardier-beetle-sprays-hot-chemical-mixture/",
        "slug": "bombardier-beetle-pulsed-combustion-drug-injection",
    },
    {
        "organism": "Red-eyed tree frog",
        "organism_scientific": "Agalychnis callidryas",
        "kingdom": "Animal",
        "habitat": "Tropical rainforests of Central and South America",
        "biological_function": "This frog can cling to smooth, wet leaves using toe pads that work via a wet adhesion mechanism: a thin mucus layer between toe pad and leaf creates surface tension and capillary forces. Hexagonal epithelial cells separated by channels allow excess fluid to drain, maintaining suction even when the surface is wet.",
        "biomimicry_taxonomy_group": "Attach",
        "biomimicry_taxonomy_subgroup": "Attach to wet surfaces",
        "human_application": "Wet-condition adhesive pads for surgical robots, micro-manipulation of delicate wet objects in manufacturing, and design of gripping surfaces for amphibious robots.",
        "real_world_products": "Tree frog-inspired wet adhesive gripper (Cornell University), surgical instrument grip research",
        "industry_tags": "robotics, medical devices, manufacturing",
        "key_principle": "Structured soft surfaces with drainage channels maintain a thin, uniform fluid film that generates capillary adhesion while preventing hydroplaning — works best on smooth surfaces in wet conditions.",
        "source_url": "https://asknature.org/strategy/toe-pads-adhere-to-wet-surfaces/",
        "slug": "tree-frog-wet-adhesion-surgical-robots",
    },
    {
        "organism": "Mantis shrimp",
        "organism_scientific": "Odontodactylus scyllarus",
        "kingdom": "Animal",
        "habitat": "Shallow tropical and subtropical marine environments",
        "biological_function": "The mantis shrimp's striking club accelerates at 10,000 g and strikes prey at 23 m/s, generating cavitation bubbles that deliver a second impact when they collapse. Despite delivering thousands of strikes, the club never shatters. Its structure — helicoidal fiber layers around a ceramic-like impact surface — distributes crack propagation in all directions simultaneously.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Resist fracture",
        "human_application": "Impact-resistant composite materials for military helmets, football pads, aircraft panels, and body armor that are simultaneously hard and crack-resistant.",
        "real_world_products": "UCSB helicoidal composite research, Sikorsky helicopter panel testing, impact-resistant sporting equipment prototypes",
        "industry_tags": "defense, aerospace, sports equipment, materials science",
        "key_principle": "A Bouligand (helicoidal) fiber architecture rotates fiber orientation through each lamina, redirecting crack propagation so no single crack plane can propagate through the full thickness.",
        "source_url": "https://asknature.org/strategy/club-withstands-extreme-impacts/",
        "slug": "mantis-shrimp-helicoidal-impact-resistant-composites",
    },
    {
        "organism": "Desert locust",
        "organism_scientific": "Schistocerca gregaria",
        "kingdom": "Animal",
        "habitat": "Arid and semi-arid regions of Africa, the Middle East, and South Asia",
        "biological_function": "Locusts can fly in dense swarms of millions without colliding. Each locust has a specialized visual neuron — the Lobula Giant Movement Detector (LGMD) — that fires only when an object is approaching on a collision course, triggering an evasive maneuver in under 50 milliseconds.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect approaching objects",
        "human_application": "Collision-avoidance systems for autonomous vehicles, drones, and robots that must react faster than conventional camera-based AI systems. The LGMD architecture requires far less computation than deep learning approaches.",
        "real_world_products": "Locust-inspired collision avoidance chip (University of Lincoln), agricultural drone obstacle avoidance systems",
        "industry_tags": "robotics, transportation, defense, agriculture",
        "key_principle": "A sparse, neuromorphic sensor that responds only to expanding visual stimuli (looming objects) enables ultra-fast collision detection with minimal computational overhead — contrast with dense camera arrays that process entire scenes.",
        "source_url": "https://asknature.org/strategy/visual-neurons-detect-collision-course-objects/",
        "slug": "locust-collision-detection-autonomous-vehicles",
    },
    {
        "organism": "Pitcher plant (Nepenthes)",
        "organism_scientific": "Nepenthes rafflesiana",
        "kingdom": "Plant",
        "habitat": "Tropical peat swamps and heath forests of Borneo",
        "biological_function": "The pitcher plant traps insects using a slippery rim (peristome) that becomes nearly frictionless when wet. The surface has interlocking microstructures that trap a thin water film, creating an aquaplaning effect that sends insects sliding into the digestive fluid below.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Manage surface friction",
        "human_application": "SLIPS (Slippery Liquid-Infused Porous Surfaces) — coatings that repel virtually any liquid or solid, including ice, oil, blood, and bacteria. Applications include ice-free aircraft wings, self-cleaning medical tubing, and anti-fouling ship hulls.",
        "real_world_products": "SLIPS Technologies (Harvard spinout), LiquiGlide bottle coating, Adaptive Surface Technologies coatings",
        "industry_tags": "aerospace, medical devices, marine engineering, food packaging",
        "key_principle": "A structured porous surface infused with a lubricating liquid creates a molecularly smooth, replenishing interface that cannot be displaced by most solids or liquids — far more durable than dry superhydrophobic surfaces.",
        "source_url": "https://asknature.org/strategy/slippery-rim-traps-insects/",
        "slug": "pitcher-plant-slippery-surface-slips-coating",
    },
    {
        "organism": "Peregrine falcon",
        "organism_scientific": "Falco peregrinus",
        "kingdom": "Animal",
        "habitat": "Every continent except Antarctica; nests on cliff faces and tall buildings",
        "biological_function": "The peregrine falcon is the fastest animal on Earth, diving at over 320 km/h. Small bony tubercles in its nostrils act as baffles that redirect supersonic airflow, preventing it from forcing air into the lungs at lethal pressure — the same problem jet engines face at high speeds.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Manage airflow at high speed",
        "human_application": "Spiral ridges inside jet engine intake cones (cone spikes) that redirect airflow during high-speed flight, preventing engine compressor stall and improving fuel efficiency.",
        "real_world_products": "Whittle jet engine intake design, modern high-bypass turbofan intake geometry",
        "industry_tags": "aerospace, energy",
        "key_principle": "A precisely shaped internal baffle or spiral ridge redirects high-velocity airflow to reduce dynamic pressure at the intake, preventing compressor surge without restricting overall airflow.",
        "source_url": "https://asknature.org/strategy/nostril-tubercles-manage-airflow/",
        "slug": "peregrine-falcon-nostril-jet-engine-intake",
    },
    {
        "organism": "Cuttlefish",
        "organism_scientific": "Sepia officinalis",
        "kingdom": "Animal",
        "habitat": "Coastal waters of Europe, the Mediterranean, and West Africa",
        "biological_function": "Cuttlefish change skin color and pattern within milliseconds using three layers of specialized cells: chromatophores (pigment sacs), iridophores (structural reflectors), and leucophores (white diffusers). The result is dynamic camouflage, communication, and warning displays — all controlled by a distributed neural network in the skin itself.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Produce and control color",
        "human_application": "Flexible, color-changing displays and electronic skin for wearables, soft robots, and medical monitoring devices that change color in response to pressure, temperature, or biochemical signals.",
        "real_world_products": "MIT Media Lab color-display skin research, Cornell soft robot camouflage, Stretchable electronics with dynamic color",
        "industry_tags": "electronics, robotics, medical devices, textiles",
        "key_principle": "Layering passive structural color (iridophores) with actively controllable pigment cells (chromatophores) creates a full-gamut, real-time color system using very little energy.",
        "source_url": "https://asknature.org/strategy/skin-changes-color-for-camouflage/",
        "slug": "cuttlefish-color-changing-skin-flexible-displays",
    },
    {
        "organism": "Basking shark",
        "organism_scientific": "Cetorhinus maximus",
        "kingdom": "Animal",
        "habitat": "Temperate ocean waters worldwide",
        "biological_function": "The basking shark filter-feeds on plankton by swimming with its mouth open, passing up to 2,000 tonnes of water per hour through gill rakers that capture prey as small as 1.5 mm. The gill raker geometry maximizes surface area for filtration while minimizing drag and clogging.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Filter and separate materials",
        "human_application": "High-efficiency water filtration membranes and microplastic-capture systems inspired by the gill raker geometry. Also desalination membrane designs.",
        "real_world_products": "Biomimetic filtration research at MIT and TU Delft, microplastic filtration mesh concepts",
        "industry_tags": "water, environmental technology, marine engineering",
        "key_principle": "A branching, high-surface-area filter geometry with precisely tuned pore size captures target particles while allowing water to flow through with minimal resistance — passive, clog-resistant filtration.",
        "source_url": "https://asknature.org/strategy/gill-rakers-filter-plankton/",
        "slug": "basking-shark-gill-rakers-water-filtration",
    },
    {
        "organism": "Migratory monarch butterfly",
        "organism_scientific": "Danaus plexippus",
        "kingdom": "Animal",
        "habitat": "North America, overwintering in Mexican oyamel fir forests",
        "biological_function": "Monarch butterflies navigate up to 4,000 km using a time-compensated sun compass in their antennae and a magnetic sense for overcast days. They integrate multiple sensory inputs — light polarization, UV gradients, and geomagnetic field — to maintain consistent bearing over weeks.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Navigate without GPS",
        "human_application": "Bio-inspired navigation algorithms for autonomous robots and drones that must navigate in GPS-denied environments, such as underground mines, indoor spaces, or areas with signal jamming.",
        "real_world_products": "Monarch-inspired robotics navigation (Case Western University), sun-compass algorithms for AUV navigation",
        "industry_tags": "robotics, defense, agriculture",
        "key_principle": "Fusing multiple redundant orientation cues — celestial, polarization, and magnetic — with an internal time reference allows robust navigation without a global reference signal.",
        "source_url": "https://asknature.org/strategy/sun-compass-guides-migration/",
        "slug": "monarch-butterfly-navigation-gps-denied-robots",
    },
    {
        "organism": "Leafcutter ant",
        "organism_scientific": "Atta cephalotes",
        "kingdom": "Animal",
        "habitat": "Tropical and subtropical forests of Central and South America",
        "biological_function": "Leafcutter ants don't eat leaves — they use them to cultivate a specific fungus (Leucoagaricus gongylophorus) underground. The fungus breaks down cellulose the ants cannot digest, producing nutritious hyphal nodules. This is arguably the world's first agriculture, refined over 50 million years.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Use biological processes to produce food",
        "human_application": "Industrial fermentation processes and fungal biotechnology inspired by the ant-fungus mutualism. Also influences sustainable agricultural system design and multi-trophic ecosystem farming.",
        "real_world_products": "EcoloGreen fungal biofertilizer research, multi-trophic vertical farming concepts, cellulose-to-nutrient bioconversion processes",
        "industry_tags": "agriculture, biotechnology, food science",
        "key_principle": "Cultivating a single, optimized microbial partner in a controlled environment converts otherwise indigestible raw materials into targeted nutritional outputs — a highly efficient closed-loop production system.",
        "source_url": "https://asknature.org/strategy/ants-cultivate-fungi-for-food/",
        "slug": "leafcutter-ant-fungal-farming-sustainable-agriculture",
    },
    {
        "organism": "Bone (cortical)",
        "organism_scientific": "Homo sapiens / general vertebrate",
        "kingdom": "Animal",
        "habitat": "Internal skeleton of vertebrate animals",
        "biological_function": "Cortical bone achieves a remarkable combination of stiffness and toughness through a hierarchical composite structure: collagen fibers (flexible) are mineralized with hydroxyapatite crystals (stiff) at the nano scale, then organized into osteons at the micro scale, then into lamellar sheets — each level contributing to crack resistance.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Optimize composite structures",
        "human_application": "Hierarchical composite materials for aerospace, orthopedic implants, and lightweight structural engineering that combine toughness and stiffness — properties that are normally trade-offs in conventional materials.",
        "real_world_products": "Bone-inspired composite research at MIT and ETH Zurich, bio-inspired ceramic-polymer composites for dental implants",
        "industry_tags": "aerospace, medical devices, materials science",
        "key_principle": "Staggered, mineralized fibrils arranged hierarchically across multiple length scales create crack-deflection and energy-dissipation mechanisms that prevent brittle fracture while maintaining high stiffness.",
        "source_url": "https://asknature.org/strategy/bone-combines-stiffness-and-toughness/",
        "slug": "bone-hierarchical-composite-aerospace-materials",
    },
    {
        "organism": "Saguaro cactus",
        "organism_scientific": "Carnegiea gigantea",
        "kingdom": "Plant",
        "habitat": "Sonoran Desert of Arizona and northwestern Mexico",
        "biological_function": "The saguaro's pleated, accordion-like trunk expands to store up to 750 liters of water after rain, then slowly contracts as the plant uses the stored water during drought. The ribbed structure also increases surface area for cooling and is structural strong in compression.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Store and release fluids",
        "human_application": "Foldable, expandable structures for packaging, deployable space structures, collapsible water storage vessels, and flexible electronic devices.",
        "real_world_products": "Accordion-fold packaging concepts, NASA deployable solar panels with pleated geometry, foldable battery architectures",
        "industry_tags": "packaging, aerospace, energy, architecture",
        "key_principle": "A pleated or corrugated geometry allows large, reversible volume changes while maintaining structural integrity — the fold geometry distributes strain so no single point bears catastrophic stress.",
        "source_url": "https://asknature.org/strategy/accordion-like-trunk-stores-water/",
        "slug": "saguaro-cactus-pleated-structure-expandable-design",
    },
    {
        "organism": "Archerfish",
        "organism_scientific": "Toxotes jaculatrix",
        "kingdom": "Animal",
        "habitat": "Brackish and freshwater mangroves of South and Southeast Asia",
        "biological_function": "The archerfish shoots precisely aimed jets of water at insects sitting on vegetation above the water surface, knocking them in for eating. It corrects for refraction at the air-water interface and adjusts jet power based on target distance — all with a brain the size of a pea.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Correct for optical distortion",
        "human_application": "Precision liquid-jet systems for micro-manufacturing, targeted drug delivery, and inkjet printing nozzle design. Also inspires refraction-correcting algorithms in underwater imaging systems.",
        "real_world_products": "Archerfish-inspired inkjet nozzle research, precision liquid-jet cutting tools",
        "industry_tags": "manufacturing, medical devices, electronics",
        "key_principle": "Computing the refraction correction for an object seen through an interface — and adjusting output force to compensate for variable-range targets — enables precise fluid-jet targeting without mechanical aiming systems.",
        "source_url": "https://asknature.org/strategy/fish-shoots-jets-of-water-to-capture-prey/",
        "slug": "archerfish-precision-liquid-jet-inkjet-printing",
    },
    {
        "organism": "Venus flytrap",
        "organism_scientific": "Dionaea muscipula",
        "kingdom": "Plant",
        "habitat": "Coastal plain bogs of North and South Carolina",
        "biological_function": "The Venus flytrap snaps shut in 100 milliseconds — one of the fastest movements in the plant kingdom. It uses a bistable elastic snap-through mechanism: the leaf is pre-stressed into a curved shape that snaps to an opposite curvature when trigger hairs are stimulated, like a curved ruler being pushed past its elastic midpoint.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Produce rapid movement",
        "human_application": "Snap-through actuators in soft robotics, deployable aerospace structures, mechanical logic gates, and microsurgical grippers that close rapidly without powered actuation.",
        "real_world_products": "Harvard soft robot gripper (snap-through actuator), deployable satellite antenna mechanisms, bistable mechanical memory elements",
        "industry_tags": "robotics, aerospace, medical devices",
        "key_principle": "A bistable elastic shell pre-stressed past its elastic midpoint stores energy in a curved geometry and releases it explosively when triggered, producing rapid movement without motors.",
        "source_url": "https://asknature.org/strategy/trap-closes-with-snap-buckling/",
        "slug": "venus-flytrap-snap-through-soft-robotics",
    },
    {
        "organism": "Abalone shell (Red abalone)",
        "organism_scientific": "Haliotis rufescens",
        "kingdom": "Animal",
        "habitat": "Rocky kelp forest habitats of the California coast",
        "biological_function": "Abalone shell (nacre) is made from the same calcium carbonate as blackboard chalk, yet is 3,000 times tougher. Microscopic hexagonal platelets of aragonite are stacked with nanoscale polymer layers between them. Cracks must deflect and travel around thousands of platelets rather than propagating straight through.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Resist fracture",
        "human_application": "Ultra-tough ceramic composites for body armor, cutting tools, and protective coatings that are hard yet resistant to catastrophic fracture — the exact combination difficult to achieve in conventional ceramics.",
        "real_world_products": "Nacre-inspired ceramic composites (MIT), abalone-inspired body armor panels, biomimetic dental enamel coatings",
        "industry_tags": "defense, medical devices, materials science",
        "key_principle": "Arranging brittle platelets in a staggered, brick-and-mortar architecture with compliant organic mortar forces cracks to deflect at every platelet interface, spreading fracture energy over an enormous surface area.",
        "source_url": "https://asknature.org/strategy/shell-is-extremely-tough/",
        "slug": "abalone-nacre-tough-ceramic-composites",
    },
    {
        "organism": "Bioluminescent dinoflagellate",
        "organism_scientific": "Noctiluca scintillans",
        "kingdom": "Protist",
        "habitat": "Coastal marine waters worldwide",
        "biological_function": "These single-celled organisms produce cold blue light through a luciferin-luciferase reaction triggered by mechanical disturbance of the water. The light is produced with near-100% efficiency — almost no energy is wasted as heat, unlike incandescent bulbs which waste 90% of energy as heat.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Produce light efficiently",
        "human_application": "High-efficiency bioluminescent lighting systems, biochemical sensors, and medical imaging agents that produce light without heat. Luciferase is widely used in biomedical research as a reporter gene.",
        "real_world_products": "Luciferase reporter assays (widely used in pharmaceuticals), GlowSolutions bioluminescent lighting research, Jellyfish-inspired emergency lighting",
        "industry_tags": "biotechnology, medical devices, environmental technology",
        "key_principle": "Enzymatic oxidation of luciferin produces electronically excited oxyluciferin, which relaxes to ground state by emitting a photon — a chemical process with near-unity quantum efficiency operating at ambient temperature.",
        "source_url": "https://asknature.org/strategy/bioluminescence-produces-cold-light/",
        "slug": "dinoflagellate-bioluminescence-efficient-lighting",
    },
    {
        "organism": "Dung beetle",
        "organism_scientific": "Scarabaeus satyrus",
        "kingdom": "Animal",
        "habitat": "Sub-Saharan African savanna",
        "biological_function": "On dark, cloudy nights when stars are invisible, the dung beetle navigates in a straight line by detecting the faint polarization pattern of the Milky Way — the only animal known to use the galaxy for navigation. This prevents it from circling back and losing its dung ball to competitors.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Navigate using light polarization",
        "human_application": "Compact polarized-light navigation sensors for autonomous vehicles and robots that need to navigate without GPS — particularly in featureless open environments or GPS-denied areas.",
        "real_world_products": "Desert locust-inspired polarization compass (University of Edinburgh), polarimetric navigation for AUVs",
        "industry_tags": "robotics, transportation, defense",
        "key_principle": "Detecting the polarization pattern of scattered light (from the sun, moon, or Milky Way) provides a global directional reference that is available even on overcast nights and in GPS-denied environments.",
        "source_url": "https://asknature.org/strategy/beetle-navigates-by-milky-way/",
        "slug": "dung-beetle-polarized-light-navigation",
    },
    {
        "organism": "Blue whale",
        "organism_scientific": "Balaenoptera musculus",
        "kingdom": "Animal",
        "habitat": "All major oceans",
        "biological_function": "Blue whales communicate across ocean basins using ultra-low frequency (10-40 Hz) sound that travels thousands of kilometers. The calls are produced without vocal cords via a U-fold of laryngeal tissue that vibrates as air recirculates — no air is lost during vocalization, an essential adaptation for diving mammals.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Produce and transmit sound",
        "human_application": "Long-range underwater acoustic communication systems, low-frequency sonar design, and vocal prosthetics inspired by the airless vocalization mechanism.",
        "real_world_products": "NOAA SOSUS-inspired underwater monitoring arrays, low-frequency sonar for submarine communication",
        "industry_tags": "marine engineering, defense, medical devices",
        "key_principle": "A U-fold of tissue that vibrates through air recirculation — not airflow — enables sound production at depth where compressed air cannot be spared, applicable to any acoustic system requiring efficient, contained vibration.",
        "source_url": "https://asknature.org/strategy/blue-whale-calls-travel-across-oceans/",
        "slug": "blue-whale-low-frequency-underwater-communication",
    },
    {
        "organism": "Bone-eating worm (Osedax)",
        "organism_scientific": "Osedax mucofloris",
        "kingdom": "Animal",
        "habitat": "Deep ocean floor around whale falls",
        "biological_function": "Osedax worms have no mouth, gut, or digestive organs. Instead, they grow root-like structures into whale bones that secrete acid to dissolve the bone, releasing lipids and proteins. Symbiotic bacteria in the roots metabolize the nutrients and feed the worm — a completely different model of digestion.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Use symbiosis for metabolism",
        "human_application": "Inspiration for chemical recycling processes that use acid-secreting biological agents to break down composite materials, and for designing synthetic symbiotic systems in bioprocessing.",
        "real_world_products": "Acid-assisted composite recycling research, bioleaching processes for metal recovery",
        "industry_tags": "biotechnology, environmental technology, materials science",
        "key_principle": "Outsourcing complex metabolic functions to specialized symbiotic microorganisms allows the host organism to access energy sources it could never process alone — a division-of-labor principle applicable to industrial bioprocessing.",
        "source_url": "https://asknature.org/strategy/worm-digests-bone-without-a-gut/",
        "slug": "osedax-worm-symbiotic-digestion-bioprocessing",
    },
    {
        "organism": "Indian flying fox bat",
        "organism_scientific": "Pteropus giganteus",
        "kingdom": "Animal",
        "habitat": "South and Southeast Asian forests",
        "biological_function": "Bat wings are built from a thin, highly elastic membrane stretched over elongated finger bones. The membrane has anisotropic stiffness — stiff along the wing span, flexible across it — and contains tiny hair sensors that detect airflow separation, triggering micro-adjustments 100 times per second to maintain optimal aerodynamics.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Generate and control lift",
        "human_application": "Morphing aircraft wings that change shape in flight to optimize aerodynamics at different speeds, reducing fuel consumption. Also inspires drone wings that auto-correct their shape in turbulent conditions.",
        "real_world_products": "DARPA morphing wing research, FlexSys Mission Adaptive Compliant Wing, bat-inspired MAV (micro air vehicle) designs",
        "industry_tags": "aerospace, robotics",
        "key_principle": "A membrane wing with embedded flow sensors and anisotropic compliance allows continuous, passive shape adaptation to airflow — achieving near-optimal aerodynamics across a wide speed range without mechanical actuators.",
        "source_url": "https://asknature.org/strategy/wing-membrane-enables-precise-flight/",
        "slug": "bat-wing-membrane-morphing-aircraft-wings",
    },
    {
        "organism": "Glass sponge (Euplectella aspergillum)",
        "organism_scientific": "Euplectella aspergillum",
        "kingdom": "Animal",
        "habitat": "Deep ocean floor, 100-1000m depth, Indo-Pacific",
        "biological_function": "This deep-sea sponge builds a cylindrical cage of glass (silica spicules) that withstands the crushing pressure of the deep ocean. Its lattice structure — diagonal bracing in a square grid — is identical to modern engineering cross-bracing. It also concentrates optical fibers that transmit bioluminescent light for luring prey.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Build strong structures from brittle materials",
        "human_application": "Diagonal cross-bracing patterns for architectural skyscrapers and bridges that achieve maximum stiffness with minimum material. Also inspires optical fiber routing in complex geometries.",
        "real_world_products": "Hearst Tower diagonal bracing (inspired by structural analysis of glass sponge), MIT structural lattice optimization",
        "industry_tags": "architecture, materials science, aerospace",
        "key_principle": "Diagonal bracing of a square lattice — a checkerboard of X-braces — is the most material-efficient way to resist shear forces in a lightweight structure, a principle the sponge evolved before engineers derived it mathematically.",
        "source_url": "https://asknature.org/strategy/skeleton-resists-twisting-and-bending/",
        "slug": "glass-sponge-lattice-skyscraper-diagonal-bracing",
    },
    {
        "organism": "Spittlebug (Philaenus spumarius)",
        "organism_scientific": "Philaenus spumarius",
        "kingdom": "Animal",
        "habitat": "Meadows and gardens across Europe and North America",
        "biological_function": "The spittlebug nymph wraps itself in foam made from plant sap and a foaming agent secreted from its abdomen. The foam stabilizes at the correct bubble size to insulate the insect against temperature extremes and desiccation — a self-made microhabitat from cheap, locally available materials.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Create insulating structures",
        "human_application": "Biodegradable foam insulation and packaging materials that use plant-derived surfactants rather than petroleum-based blowing agents. Also inspires self-generating foam barriers for chemical containment.",
        "real_world_products": "Plant-based foam packaging (Ecovative Design), natural surfactant foam research",
        "industry_tags": "packaging, construction, environmental technology",
        "key_principle": "Combining a locally available foaming agent with a surface-active protein creates a stable, size-tunable foam at ambient temperature — a zero-energy insulation fabrication process.",
        "source_url": "https://asknature.org/strategy/foam-protects-from-temperature-extremes/",
        "slug": "spittlebug-foam-biodegradable-insulation-packaging",
    },
    {
        "organism": "Bone-dry wood frog",
        "organism_scientific": "Rana sylvatica",
        "kingdom": "Animal",
        "habitat": "Northern forests of North America, as far north as the Arctic Circle",
        "biological_function": "The wood frog can survive being frozen solid. As temperatures drop, it floods its cells with glucose (a natural antifreeze), which prevents ice crystals from forming inside cells. Ice forms only outside cells, in extracellular spaces, and the frog's heart stops beating for weeks until spring thaw.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Survive extreme cold",
        "human_application": "Cryopreservation of organs for transplant, preservation of blood products, and long-term preservation of biological samples and pharmaceuticals without damage from ice crystal formation.",
        "real_world_products": "Organ preservation solutions using glucose-based cryoprotectants, BioLife Solutions cell culture media, cryogenic storage protocols",
        "industry_tags": "medical devices, biotechnology, food science",
        "key_principle": "Rapidly increasing intracellular solute concentration (cryoprotectant loading) before freezing depresses the freezing point inside cells and prevents ice nucleation in cytoplasm — allowing controlled extracellular ice formation without cell death.",
        "source_url": "https://asknature.org/strategy/wood-frog-survives-freezing/",
        "slug": "wood-frog-freeze-tolerance-cryopreservation",
    },
    {
        "organism": "Desert ant (Cataglyphis fortis)",
        "organism_scientific": "Cataglyphis fortis",
        "kingdom": "Animal",
        "habitat": "Saharan and Middle Eastern salt pans and desert flats",
        "biological_function": "Desert ants forage solo, ranging up to 500 meters from the nest with no landmarks in featureless terrain. They navigate home by path integration — continuously tracking the direction and distance of each step using their compound eyes and counting steps with a built-in pedometer — arriving within meters of their nest entrance.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Track position without landmarks",
        "human_application": "Dead-reckoning navigation algorithms for robots and autonomous vehicles that must navigate in GPS-denied environments without landmarks, using only velocity and heading sensors.",
        "real_world_products": "Ant-inspired insect robot navigation (Holk Cruse, Bielefeld), AntBot robot (CNRS/Aix-Marseille), step-counter odometry for underground robots",
        "industry_tags": "robotics, defense, mining",
        "key_principle": "Continuously integrating heading direction (from a polarized-light compass) and step count gives a running home vector that is always up to date — a simple, power-efficient navigation strategy for featureless environments.",
        "source_url": "https://asknature.org/strategy/desert-ant-finds-way-home-without-landmarks/",
        "slug": "desert-ant-path-integration-robot-navigation",
    },
    {
        "organism": "Sea cucumber",
        "organism_scientific": "Cucumaria frondosa",
        "kingdom": "Animal",
        "habitat": "Cold Atlantic and Pacific ocean floors",
        "biological_function": "Sea cucumbers can rapidly change their body stiffness from rigid (when threatened) to soft and fluid (to squeeze through cracks). The connective tissue contains collagen fibers whose cross-linking density is controlled by chemical signals — becoming stiff or soft within seconds, at any intermediate state.",
        "biomimicry_taxonomy_group": "Modify",
        "biomimicry_taxonomy_subgroup": "Change mechanical properties on demand",
        "human_application": "Shape-changing neural implants that are rigid during insertion (minimizing tissue damage) then soften to match brain tissue stiffness once implanted, reducing long-term immune response and scar formation.",
        "real_world_products": "CASE nanocomposite implants (Case Western Reserve), variable-stiffness catheter research, tunable stiffness soft robots",
        "industry_tags": "medical devices, robotics",
        "key_principle": "Reinforcing a polymer matrix with nanofibers that can be chemically switched between bonded (stiff) and unbonded (soft) states creates a material whose modulus spans orders of magnitude — tunable, reversible, and biocompatible.",
        "source_url": "https://asknature.org/strategy/body-wall-changes-stiffness/",
        "slug": "sea-cucumber-variable-stiffness-neural-implants",
    },
    {
        "organism": "Lily pad (Victoria amazonica)",
        "organism_scientific": "Victoria amazonica",
        "kingdom": "Plant",
        "habitat": "Amazon River basin, South America",
        "biological_function": "The giant Amazonian lily pad can support the weight of a small child (up to 40 kg) on its surface, despite being made of thin, water-filled tissue. The underside has a radiating rib structure alternating with air-filled chambers that provides enormous flexural rigidity with minimal material.",
        "biomimicry_taxonomy_group": "Make",
        "biomimicry_taxonomy_subgroup": "Build lightweight load-bearing structures",
        "human_application": "Structural design of lightweight floor plates, roof panels, and shell structures in architecture and aerospace that maximize load-bearing capacity relative to material weight.",
        "real_world_products": "Crystal Palace (Joseph Paxton, inspired by lily pad ribs), ribbed concrete slab design, lightweight aerospace floor panels",
        "industry_tags": "architecture, aerospace, materials science",
        "key_principle": "Alternating load-bearing ribs with lightweight infill panels (whether air, lightweight foam, or low-density material) creates a composite slab with extremely high stiffness-to-weight ratio — the ribs handle bending stress, the infill handles shear.",
        "source_url": "https://asknature.org/strategy/leaf-supports-heavy-loads/",
        "slug": "lily-pad-ribbed-structure-lightweight-architecture",
    },
    {
        "organism": "Turritopsis dohrnii jellyfish",
        "organism_scientific": "Turritopsis dohrnii",
        "kingdom": "Animal",
        "habitat": "Mediterranean Sea and tropical oceans worldwide",
        "biological_function": "This jellyfish is effectively biologically immortal — when stressed, it reverts from its adult medusa form back to a juvenile polyp stage, restarting its life cycle indefinitely. This transdifferentiation process converts specialized adult cells back to pluripotent stem cells.",
        "biomimicry_taxonomy_group": "Modify",
        "biomimicry_taxonomy_subgroup": "Reverse cellular differentiation",
        "human_application": "Regenerative medicine research into induced pluripotent stem cells (iPSCs) — reprogramming adult cells back to a stem cell state to grow replacement tissues and organs, without using embryonic cells.",
        "real_world_products": "Yamanaka factor iPSC technology (Nobel Prize 2012), laboratory-grown tissues and organoids, stem cell therapies in clinical trials",
        "industry_tags": "biotechnology, medical devices",
        "key_principle": "Applying a defined set of transcription factors to a differentiated adult cell can reset its epigenetic program to a pluripotent state — reversing the developmental clock and enabling the cell to differentiate into any tissue type.",
        "source_url": "https://asknature.org/strategy/jellyfish-reverses-its-life-cycle/",
        "slug": "immortal-jellyfish-cellular-reprogramming-stem-cells",
    },
    {
        "organism": "Mangrove tree (Red mangrove)",
        "organism_scientific": "Rhizophora mangle",
        "kingdom": "Plant",
        "habitat": "Tropical and subtropical intertidal coastal zones",
        "biological_function": "Mangrove roots filter salt from seawater so effectively that the tree can drink pure saltwater and excrete only fresh water. The root cell membranes have ultra-selective ion channels that block sodium while allowing water molecules to pass — a near-perfect desalination membrane operating without pressure.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Filter and purify water",
        "human_application": "Biomimetic desalination membranes with aquaporin proteins embedded in lipid bilayers that dramatically reduce the energy required to purify seawater compared to conventional reverse osmosis.",
        "real_world_products": "Aquaporin A/S (Denmark) biomimetic desalination membranes, AquaZ aquaporin water treatment, IDE Technologies aquaporin pilot plants",
        "industry_tags": "water, environmental technology, energy",
        "key_principle": "Aquaporin protein channels create a single-file pathway that water molecules can traverse in milliseconds while ion size and charge prevent salt passage — achieving near-perfect selectivity with minimal energy, unlike pressure-driven membrane systems.",
        "source_url": "https://asknature.org/strategy/roots-filter-salt-from-seawater/",
        "slug": "mangrove-root-aquaporin-desalination-membranes",
    },
    {
        "organism": "Bees (honeybee swarm)",
        "organism_scientific": "Apis mellifera",
        "kingdom": "Animal",
        "habitat": "Worldwide, wherever flowers bloom",
        "biological_function": "When a honeybee colony scouts for a new nest site, hundreds of scouts investigate different options and report back with waggle dances of varying intensity. The colony reaches a quorum decision — with no bee having seen all options — selecting the best site within hours. No single bee is in charge; the intelligence is collective.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Make collective decisions",
        "human_application": "Swarm intelligence algorithms for distributed problem-solving in robotics, network routing (internet traffic management), and optimization of logistics and supply chains.",
        "real_world_products": "Ant Colony Optimization (ACO) algorithms for logistics, Bee Algorithm for manufacturing scheduling, swarm robotics platforms (Kilobot, Crazyflie drones)",
        "industry_tags": "robotics, transportation, computing",
        "key_principle": "A positive-feedback quorum-sensing mechanism allows distributed agents to reach consensus on the best option among many — with no central coordinator — by amplifying signals proportional to option quality.",
        "source_url": "https://asknature.org/strategy/swarm-makes-collective-decisions/",
        "slug": "bee-swarm-intelligence-distributed-optimization",
    },
    {
        "organism": "Flying squirrel",
        "organism_scientific": "Glaucomys sabrinus",
        "kingdom": "Animal",
        "habitat": "North American coniferous and mixed forests",
        "biological_function": "The flying squirrel glides up to 90 meters by extending a skin membrane (patagium) between its front and hind legs. It steers with its tail and adjusts membrane tension mid-glide, landing on vertical tree trunks with precision. The patagium folds away completely when not in use.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Generate unpowered lift",
        "human_application": "Wingsuits for base jumping and skydiving, compact deployable parachute systems, and flexible membrane wing designs for micro air vehicles (MAVs) that fold for storage.",
        "real_world_products": "Squirrel suit wingsuit design, membrane wing MAVs (Stanford AFOSR research), compact deployable aerodynamic systems",
        "industry_tags": "aerospace, defense, sports equipment",
        "key_principle": "A tensioned membrane wing between limbs creates lift through glide rather than powered flight, achieves precise steering through differential tension, and collapses to near-zero drag when not in use.",
        "source_url": "https://asknature.org/strategy/gliding-membrane-enables-flight/",
        "slug": "flying-squirrel-patagium-wingsuit-membrane-wing",
    },
    {
        "organism": "Baobab tree",
        "organism_scientific": "Adansonia digitata",
        "kingdom": "Plant",
        "habitat": "African savanna, dry deciduous forests",
        "biological_function": "The baobab stores up to 120,000 liters of water in its fibrous, spongy trunk — enough to sustain it through long dry seasons. Its bark is fire-resistant, its root system is shallow but vast, and it can re-sprout from its base even if burned. It can live over 2,000 years.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Store water in tissue",
        "human_application": "Water storage architecture in arid-region building design, sponge-core structural materials that store and release water for passive evaporative cooling, and fire-resistant building materials.",
        "real_world_products": "Baobab-inspired water-storing urban design concepts, evaporative cooling architectural systems, fire-resistant composite wood panels",
        "industry_tags": "architecture, water, construction",
        "key_principle": "A fibrous, low-density tissue that absorbs and releases large volumes of water without structural collapse enables passive thermal regulation through evaporation — a natural heat sink that requires no energy input.",
        "source_url": "https://asknature.org/strategy/trunk-stores-large-amounts-of-water/",
        "slug": "baobab-water-storage-evaporative-cooling-architecture",
    },
    {
        "organism": "Sea snail (Cyphoma gibbosum)",
        "organism_scientific": "Cyphoma gibbosum",
        "kingdom": "Animal",
        "habitat": "Caribbean coral reefs",
        "biological_function": "The flamingo tongue snail moves across sea fans (gorgonian coral) by secreting a mucus trail with precisely tuned viscoelastic properties — stiff enough to prevent the snail from sliding on vertical surfaces, yet fluid enough to release cleanly with a peeling motion. No residue is left on the coral.",
        "biomimicry_taxonomy_group": "Attach",
        "biomimicry_taxonomy_subgroup": "Move while attached",
        "human_application": "Mucus-inspired reversible adhesives for climbing robots and transportation vehicles on complex surfaces, and medical wound dressings that adhere gently yet release cleanly.",
        "real_world_products": "Viscoelastic adhesive research for soft robotics, medical hydrogel wound dressings, wall-climbing robot adhesives",
        "industry_tags": "robotics, medical devices, materials science",
        "key_principle": "A viscoelastic fluid that behaves as a solid under slow shear (preventing sliding) but flows under fast peel (enabling clean release) creates an ideal reversible adhesive — tunable simply by adjusting polymer chain length and density.",
        "source_url": "https://asknature.org/strategy/mucus-enables-movement-on-vertical-surfaces/",
        "slug": "sea-snail-mucus-viscoelastic-adhesive-climbing-robots",
    },
    {
        "organism": "Lichen",
        "organism_scientific": "Cladonia rangiferina",
        "kingdom": "Fungi",
        "habitat": "Arctic tundra, exposed rock faces worldwide",
        "biological_function": "Lichen is a symbiosis between fungus and photosynthetic algae or cyanobacteria. The fungus provides shelter and mineral access; the algae provides sugars via photosynthesis. Together they colonize bare rock — breaking down stone with acids and generating soil — in environments neither could survive alone.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Pioneer harsh environments",
        "human_application": "Mutualistic biofilm engineering for bioremediation of contaminated soils, biomineralization for biocement, and CO2-sequestering living building materials.",
        "real_world_products": "BioMASON biocement (living bricks), Ecovative mycelium packaging (fungal-plant symbiosis), rock-bioweathering agents for soil generation",
        "industry_tags": "environmental technology, construction, biotechnology",
        "key_principle": "Pairing organisms with complementary metabolisms in a single composite organism creates a unit that exceeds what either could do alone — a template for engineering mutualistic microbial consortia for industrial bioprocessing.",
        "source_url": "https://asknature.org/strategy/lichen-colonizes-bare-rock/",
        "slug": "lichen-symbiosis-biocement-living-building-materials",
    },
    {
        "organism": "Bombardier frog (Bombina variegata)",
        "organism_scientific": "Bombina variegata",
        "kingdom": "Animal",
        "habitat": "Central and Eastern European forests and meadows",
        "biological_function": "The fire-bellied toad uses aposematic warning coloration — a vivid yellow-and-black belly — to advertise its toxic skin secretions to predators. When grabbed, it arches its back to display the belly, relying on the predator's learned association between color and toxicity rather than physical defense.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Signal danger through color",
        "human_application": "Warning label design and hazard communication systems based on aposematic color principles (high-contrast yellow-black), and passive safety design in vehicles and machinery.",
        "real_world_products": "ANSI safety color standards (yellow/black), ISO 7010 hazard symbols, construction safety equipment color design",
        "industry_tags": "safety, consumer products, transportation",
        "key_principle": "High-contrast color combinations — particularly yellow-black or red-black — are universally recognized as biological warning signals, making them the most effective choice for passive danger communication without verbal instruction.",
        "source_url": "https://asknature.org/strategy/warning-coloration-deters-predators/",
        "slug": "fire-bellied-toad-aposematism-safety-warning-design",
    },
    {
        "organism": "Pistol shrimp",
        "organism_scientific": "Alpheus heterochaelis",
        "kingdom": "Animal",
        "habitat": "Tropical and subtropical shallow marine habitats worldwide",
        "biological_function": "The pistol shrimp snaps its oversized claw so fast it creates a cavitation bubble that collapses at nearly 5,000°C and stuns or kills prey from a distance. The snap creates a jet of water moving at 25 m/s — all from a claw mechanism, no projectile needed.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Generate rapid force from stored energy",
        "human_application": "Micro-scale underwater cleaning devices using cavitation to remove biofilm from ship hulls and medical implants, and high-speed microfluidic mixing systems for lab-on-a-chip applications.",
        "real_world_products": "Cavitation cleaning systems for ship hulls, cavitation-based drug delivery research, microfluidic mixer designs",
        "industry_tags": "marine engineering, medical devices, manufacturing",
        "key_principle": "Spring-loaded elastic energy storage in a latch mechanism enables near-instantaneous energy release, creating water jets and cavitation bubbles far beyond what continuous-force muscles could generate — a general template for power-amplified micro-actuators.",
        "source_url": "https://asknature.org/strategy/snapping-claw-creates-cavitation-bubble/",
        "slug": "pistol-shrimp-cavitation-cleaning-microfluidics",
    },
    {
        "organism": "Homing pigeon",
        "organism_scientific": "Columba livia domestica",
        "kingdom": "Animal",
        "habitat": "Worldwide; domesticated from cliff-dwelling rock pigeons",
        "biological_function": "Homing pigeons can find their way home from 1,800 km away using a combination of magnetic sense, sun compass, olfactory maps, and landmark recognition. They build a mental map of their home region rather than following a single signal — allowing them to reroute around obstacles.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Build and use cognitive maps",
        "human_application": "Cognitive mapping algorithms for autonomous robots and self-driving vehicles that build internal spatial representations of their environment, enabling rerouting and goal-directed navigation.",
        "real_world_products": "SLAM (Simultaneous Localization and Mapping) algorithms used in all modern autonomous vehicles, ROS (Robot Operating System) navigation stack",
        "industry_tags": "robotics, transportation, defense",
        "key_principle": "Fusing multiple redundant sensory modalities into a single probabilistic spatial model — rather than relying on any one sensor — creates a navigation system that is robust to individual sensor failure and works in diverse environments.",
        "source_url": "https://asknature.org/strategy/pigeon-navigates-using-multiple-cues/",
        "slug": "homing-pigeon-cognitive-mapping-autonomous-navigation",
    },
    {
        "organism": "Electric eel",
        "organism_scientific": "Electrophorus electricus",
        "kingdom": "Animal",
        "habitat": "Murky freshwater rivers and floodplains of South America",
        "biological_function": "The electric eel generates up to 860 volts using thousands of electrocytes — modified muscle cells stacked like batteries in series. Each cell generates only a small voltage, but stacking thousands multiplies the effect. The organ is also used for electrolocation and communication at low voltages.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Generate and store electrical energy",
        "human_application": "Soft, flexible power sources (biobatteries) inspired by the stacked-electrocyte design, and electrolocation sensors for autonomous underwater vehicles operating in turbid water.",
        "real_world_products": "Soft hydrogel biobattery (Yale University), electrolocation AUV sensors, ionic polymer-metal composite actuators",
        "industry_tags": "energy, robotics, medical devices",
        "key_principle": "Stacking ion-gradient generators in series multiplies voltage while parallel arrays multiply current — the same electrical engineering principle as batteries, but implemented in soft, biocompatible tissue with ionic rather than electron flow.",
        "source_url": "https://asknature.org/strategy/electric-organ-generates-high-voltage/",
        "slug": "electric-eel-stacked-electrocytes-soft-biobattery",
    },
    {
        "organism": "Dragonfly",
        "organism_scientific": "Libellula depressa",
        "kingdom": "Animal",
        "habitat": "Near freshwater habitats worldwide",
        "biological_function": "Dragonflies have four independently controlled wings, each with a corrugated cross-section. The corrugations add structural stiffness without adding weight — like a corrugated cardboard box — and create beneficial turbulence on the upper surface that delays stall. Their catch rate in aerial hunting exceeds 95%.",
        "biomimicry_taxonomy_group": "Move",
        "biomimicry_taxonomy_subgroup": "Generate efficient lift at low speeds",
        "human_application": "Corrugated wing designs for micro air vehicles (MAVs) and UAVs that must fly efficiently at low Reynolds numbers (small scale, low speed) where conventional smooth airfoils stall easily.",
        "real_world_products": "Dragonfly-inspired MAV wings (TU Delft DelFly), corrugated membrane UAV wings, 4-rotor independent control drone systems",
        "industry_tags": "aerospace, robotics, defense",
        "key_principle": "Corrugated wing cross-sections maintain structural rigidity at minimal weight while the ridges generate leading-edge vortices that keep airflow attached at high angles of attack — critical for slow, hovering, or highly maneuverable flight.",
        "source_url": "https://asknature.org/strategy/wings-are-corrugated-for-strength/",
        "slug": "dragonfly-corrugated-wings-micro-air-vehicles",
    },
    {
        "organism": "Brittle star",
        "organism_scientific": "Ophiocoma wendtii",
        "kingdom": "Animal",
        "habitat": "Caribbean and Atlantic coral reefs",
        "biological_function": "Brittlestars have no eyes, yet they can change color and seek shade in response to light changes. Their entire exoskeleton acts as a distributed eye — thousands of calcite microlenses in their arm surface are each optically perfect (minimizing spherical aberration) and collectively detect light direction.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect light using structural materials",
        "human_application": "Microlens arrays for fiber optic communications, medical endoscopes, and wide-angle camera systems where minimizing optical aberration in very small lens elements is critical.",
        "real_world_products": "Biomimetic microlens arrays (Bell Labs research), lens design for wide-field endoscopes, optical fiber coupling lens arrays",
        "industry_tags": "electronics, medical devices, materials science",
        "key_principle": "Calcite's birefringence is precisely compensated by the specific crystal orientation and lens geometry in each spicule, producing diffraction-limited performance in a lens 0.05 mm across — a lesson in leveraging material anisotropy to eliminate aberration.",
        "source_url": "https://asknature.org/strategy/skin-contains-optical-lenses/",
        "slug": "brittlestar-calcite-microlens-optical-fiber",
    },
    {
        "organism": "Platypus",
        "organism_scientific": "Ornithorhynchus anatinus",
        "kingdom": "Animal",
        "habitat": "Eastern Australian rivers and streams",
        "biological_function": "The platypus hunts underwater with its eyes closed, locating prey by detecting the tiny electric fields generated by their muscle movements. Its bill contains 40,000 electroreceptors and 60,000 mechanoreceptors, allowing it to triangulate the exact position of shrimp from 20 cm away in murky water.",
        "biomimicry_taxonomy_group": "Sense",
        "biomimicry_taxonomy_subgroup": "Detect weak electric fields",
        "human_application": "Sensitive electrochemical sensors for detecting heartbeat signals through water, non-invasive cardiac monitoring systems, and underwater object detection for military and search-and-rescue applications.",
        "real_world_products": "Electrosensory cardiac monitor concepts, electroreceptive AUV (autonomous underwater vehicle) sensors, medical capacitive sensing array designs",
        "industry_tags": "medical devices, defense, robotics",
        "key_principle": "An array of electroreceptors with overlapping fields and differential readout allows triangulation of an electric dipole source — pinpointing the precise location of a bioelectric signal without any emitted signal from the detector itself.",
        "source_url": "https://asknature.org/strategy/bill-detects-electric-fields/",
        "slug": "platypus-electroreception-underwater-sensor-cardiac",
    },
    {
        "organism": "Thorny devil lizard",
        "organism_scientific": "Moloch horridus",
        "kingdom": "Animal",
        "habitat": "Australian desert scrubland",
        "biological_function": "The thorny devil harvests water from damp sand by touching it with its feet or chin. Capillary channels between its scales carry water passively to its mouth through hygroscopic wicking — no drinking motion required. The entire scale network acts as a passive water transport system driven only by capillary pressure.",
        "biomimicry_taxonomy_group": "Process",
        "biomimicry_taxonomy_subgroup": "Transport fluids passively",
        "human_application": "Passive fluid transport channels in lab-on-a-chip microfluidic devices, capillary wicking materials for sweat management in sportswear, and passive water harvesting systems for arid environments.",
        "real_world_products": "Capillary microfluidic diagnostic chips, Coldblack moisture-wicking fabric technology, desert fog-capture research",
        "industry_tags": "medical devices, textiles, water, materials science",
        "key_principle": "A network of open capillary channels with specific geometry (width, depth, contact angle) wicks fluid passively in one direction — no pump, no power source, driven purely by surface energy gradients.",
        "source_url": "https://asknature.org/strategy/scales-collect-water-for-drinking/",
        "slug": "thorny-devil-capillary-wicking-microfluidic-chips",
    },
    {
        "organism": "Saharan silver ant",
        "organism_scientific": "Cataglyphis bombycina",
        "kingdom": "Animal",
        "habitat": "Saharan Desert sand",
        "biological_function": "Active in the hottest part of the day when most desert animals are in burrows (surface temperatures can reach 70°C), the silver ant's uniquely shaped hairs act as a full-spectrum solar reflector and thermal emitter. The triangular cross-section reflects visible and near-infrared solar radiation while emitting mid-infrared thermal radiation efficiently.",
        "biomimicry_taxonomy_group": "Protect",
        "biomimicry_taxonomy_subgroup": "Regulate body temperature through surface properties",
        "human_application": "Passive radiative cooling materials and coatings that reflect sunlight and emit heat simultaneously, keeping surfaces below ambient air temperature without energy consumption. Applications in building roofing and vehicle cooling.",
        "real_world_products": "Stanford radiative cooling film (sub-ambient cooling without energy), passive daytime radiative cooling roof membranes, SkyCool Systems commercial products",
        "industry_tags": "energy, architecture, materials science",
        "key_principle": "A surface that is simultaneously highly reflective in the solar spectrum (0.3–2.5 μm) and highly emissive in the atmospheric transparency window (8–13 μm) loses heat faster than it gains it — achieving sub-ambient cooling with zero energy input.",
        "source_url": "https://asknature.org/strategy/hair-reflects-solar-radiation/",
        "slug": "silver-ant-hairs-radiative-cooling-building-materials",
    },
]


def insert_strategies(conn):
    cursor = conn.cursor()
    inserted = 0
    skipped = 0
    for s in STRATEGIES:
        # Auto-generate slug if not provided
        if not s.get("slug"):
            s["slug"] = slugify(s["organism"])
        try:
            cursor.execute("""
                INSERT INTO strategies (
                    organism, organism_scientific, kingdom, habitat,
                    biological_function, biomimicry_taxonomy_group,
                    biomimicry_taxonomy_subgroup, human_application,
                    real_world_products, industry_tags, key_principle,
                    source_url, slug
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                s["organism"], s.get("organism_scientific"), s.get("kingdom"),
                s.get("habitat"), s.get("biological_function"),
                s.get("biomimicry_taxonomy_group"), s.get("biomimicry_taxonomy_subgroup"),
                s.get("human_application"), s.get("real_world_products"),
                s.get("industry_tags"), s.get("key_principle"),
                s.get("source_url"), s["slug"]
            ))
            inserted += 1
        except sqlite3.IntegrityError:
            skipped += 1  # Duplicate slug — already in DB
    conn.commit()
    return inserted, skipped


def main():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    create_schema(conn)
    inserted, skipped = insert_strategies(conn)
    conn.close()
    print(f"Done. Inserted {inserted} strategies, skipped {skipped} duplicates.")
    print(f"Database saved to: {os.path.abspath(DB_PATH)}")


if __name__ == "__main__":
    main()
